//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/bartt/source/repos/BartlomiejLac/IsisPapyrus/IsisPapyrus/Grammar\IsisParser.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete generic visitor for a parse tree produced
/// by <see cref="IsisParser"/>.
/// </summary>
/// <typeparam name="Result">The return type of the visit operation.</typeparam>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IIsisParserVisitor<Result> : IParseTreeVisitor<Result> {
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitProgram([NotNull] IsisParser.ProgramContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.declarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarations([NotNull] IsisParser.DeclarationsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.mainFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMainFunction([NotNull] IsisParser.MainFunctionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.declarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarationList([NotNull] IsisParser.DeclarationListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclaration([NotNull] IsisParser.DeclarationContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.declarationVariable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarationVariable([NotNull] IsisParser.DeclarationVariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.variableName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariableName([NotNull] IsisParser.VariableNameContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitType([NotNull] IsisParser.TypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.declarationFunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitDeclarationFunc([NotNull] IsisParser.DeclarationFuncContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.functionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFunctionType([NotNull] IsisParser.FunctionTypeContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArguments([NotNull] IsisParser.ArgumentsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.argumentsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgumentsList([NotNull] IsisParser.ArgumentsListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitArgument([NotNull] IsisParser.ArgumentContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.instructions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstructions([NotNull] IsisParser.InstructionsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.instructionsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstructionsList([NotNull] IsisParser.InstructionsListContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstruction([NotNull] IsisParser.InstructionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.instructionIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstructionIf([NotNull] IsisParser.InstructionIfContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.instructionLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstructionLoop([NotNull] IsisParser.InstructionLoopContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.instructionReturn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstructionReturn([NotNull] IsisParser.InstructionReturnContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.instructionBreak"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitInstructionBreak([NotNull] IsisParser.InstructionBreakContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitExpression([NotNull] IsisParser.ExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.boolExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitBoolExpression([NotNull] IsisParser.BoolExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitAndExpression([NotNull] IsisParser.AndExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.notExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitNotExpression([NotNull] IsisParser.NotExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.compareExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompareExpression([NotNull] IsisParser.CompareExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.compareOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitCompareOperator([NotNull] IsisParser.CompareOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.sumExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSumExpression([NotNull] IsisParser.SumExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.sumOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitSumOperator([NotNull] IsisParser.SumOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.multExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultExpression([NotNull] IsisParser.MultExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.multOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitMultOperator([NotNull] IsisParser.MultOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryExpression([NotNull] IsisParser.UnaryExpressionContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitUnaryOperator([NotNull] IsisParser.UnaryOperatorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitFactor([NotNull] IsisParser.FactorContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitVariable([NotNull] IsisParser.VariableContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstant([NotNull] IsisParser.ConstantContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.constants"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstants([NotNull] IsisParser.ConstantsContext context);
	/// <summary>
	/// Visit a parse tree produced by <see cref="IsisParser.constantList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	/// <return>The visitor result.</return>
	Result VisitConstantList([NotNull] IsisParser.ConstantListContext context);
}
