//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/bartt/source/repos/BartlomiejLac/IsisPapyrus/IsisPapyrus/Grammar\IsisParser.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="IsisParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.CLSCompliant(false)]
public interface IIsisParserListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterProgram([NotNull] IsisParser.ProgramContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.program"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitProgram([NotNull] IsisParser.ProgramContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.declarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarations([NotNull] IsisParser.DeclarationsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.declarations"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarations([NotNull] IsisParser.DeclarationsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.mainFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMainFunction([NotNull] IsisParser.MainFunctionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.mainFunction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMainFunction([NotNull] IsisParser.MainFunctionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.declarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationList([NotNull] IsisParser.DeclarationListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.declarationList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationList([NotNull] IsisParser.DeclarationListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] IsisParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] IsisParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.declarationVariable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationVariable([NotNull] IsisParser.DeclarationVariableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.declarationVariable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationVariable([NotNull] IsisParser.DeclarationVariableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.variableName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableName([NotNull] IsisParser.VariableNameContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.variableName"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableName([NotNull] IsisParser.VariableNameContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterType([NotNull] IsisParser.TypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.type"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitType([NotNull] IsisParser.TypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.declarationFunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclarationFunc([NotNull] IsisParser.DeclarationFuncContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.declarationFunc"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclarationFunc([NotNull] IsisParser.DeclarationFuncContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.functionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionType([NotNull] IsisParser.FunctionTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.functionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionType([NotNull] IsisParser.FunctionTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArguments([NotNull] IsisParser.ArgumentsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.arguments"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArguments([NotNull] IsisParser.ArgumentsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.argumentsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgumentsList([NotNull] IsisParser.ArgumentsListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.argumentsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgumentsList([NotNull] IsisParser.ArgumentsListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArgument([NotNull] IsisParser.ArgumentContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.argument"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArgument([NotNull] IsisParser.ArgumentContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.instructions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstructions([NotNull] IsisParser.InstructionsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.instructions"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstructions([NotNull] IsisParser.InstructionsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.instructionsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstructionsList([NotNull] IsisParser.InstructionsListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.instructionsList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstructionsList([NotNull] IsisParser.InstructionsListContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstruction([NotNull] IsisParser.InstructionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.instruction"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstruction([NotNull] IsisParser.InstructionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.instructionIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstructionIf([NotNull] IsisParser.InstructionIfContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.instructionIf"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstructionIf([NotNull] IsisParser.InstructionIfContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.instructionLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstructionLoop([NotNull] IsisParser.InstructionLoopContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.instructionLoop"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstructionLoop([NotNull] IsisParser.InstructionLoopContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.instructionReturn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstructionReturn([NotNull] IsisParser.InstructionReturnContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.instructionReturn"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstructionReturn([NotNull] IsisParser.InstructionReturnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.instructionBreak"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInstructionBreak([NotNull] IsisParser.InstructionBreakContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.instructionBreak"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInstructionBreak([NotNull] IsisParser.InstructionBreakContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] IsisParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] IsisParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.boolExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBoolExpression([NotNull] IsisParser.BoolExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.boolExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBoolExpression([NotNull] IsisParser.BoolExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAndExpression([NotNull] IsisParser.AndExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.andExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAndExpression([NotNull] IsisParser.AndExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.notExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNotExpression([NotNull] IsisParser.NotExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.notExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNotExpression([NotNull] IsisParser.NotExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.compareExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompareExpression([NotNull] IsisParser.CompareExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.compareExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompareExpression([NotNull] IsisParser.CompareExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.compareOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompareOperator([NotNull] IsisParser.CompareOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.compareOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompareOperator([NotNull] IsisParser.CompareOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.sumExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSumExpression([NotNull] IsisParser.SumExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.sumExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSumExpression([NotNull] IsisParser.SumExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.sumOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterSumOperator([NotNull] IsisParser.SumOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.sumOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitSumOperator([NotNull] IsisParser.SumOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.multExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultExpression([NotNull] IsisParser.MultExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.multExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultExpression([NotNull] IsisParser.MultExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.multOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultOperator([NotNull] IsisParser.MultOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.multOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultOperator([NotNull] IsisParser.MultOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryExpression([NotNull] IsisParser.UnaryExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryExpression([NotNull] IsisParser.UnaryExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryOperator([NotNull] IsisParser.UnaryOperatorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.unaryOperator"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryOperator([NotNull] IsisParser.UnaryOperatorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFactor([NotNull] IsisParser.FactorContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.factor"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFactor([NotNull] IsisParser.FactorContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariable([NotNull] IsisParser.VariableContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.variable"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariable([NotNull] IsisParser.VariableContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] IsisParser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.constant"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] IsisParser.ConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.constants"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstants([NotNull] IsisParser.ConstantsContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.constants"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstants([NotNull] IsisParser.ConstantsContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.constantList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstantList([NotNull] IsisParser.ConstantListContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.constantList"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstantList([NotNull] IsisParser.ConstantListContext context);
}
