//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.10.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:/Users/bartt/RiderProjects/IsisPapyrus/IsisPapyrus/Grammar\IsisParser.g4 by ANTLR 4.10.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419


using Antlr4.Runtime.Misc;
using IErrorNode = Antlr4.Runtime.Tree.IErrorNode;
using ITerminalNode = Antlr4.Runtime.Tree.ITerminalNode;
using IToken = Antlr4.Runtime.IToken;
using ParserRuleContext = Antlr4.Runtime.ParserRuleContext;

/// <summary>
/// This class provides an empty implementation of <see cref="IIsisParserListener"/>,
/// which can be extended to create a listener which only needs to handle a subset
/// of the available methods.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.10.1")]
[System.Diagnostics.DebuggerNonUserCode]
[System.CLSCompliant(false)]
public partial class IsisParserBaseListener : IIsisParserListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterProgram([NotNull] IsisParser.ProgramContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.program"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitProgram([NotNull] IsisParser.ProgramContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.mainFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMainFunction([NotNull] IsisParser.MainFunctionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.mainFunction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMainFunction([NotNull] IsisParser.MainFunctionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.declarationList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarationList([NotNull] IsisParser.DeclarationListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.declarationList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarationList([NotNull] IsisParser.DeclarationListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclaration([NotNull] IsisParser.DeclarationContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.declaration"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclaration([NotNull] IsisParser.DeclarationContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.declarationVariable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarationVariable([NotNull] IsisParser.DeclarationVariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.declarationVariable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarationVariable([NotNull] IsisParser.DeclarationVariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.variableName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariableName([NotNull] IsisParser.VariableNameContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.variableName"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariableName([NotNull] IsisParser.VariableNameContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterType([NotNull] IsisParser.TypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.type"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitType([NotNull] IsisParser.TypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.declarationFunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterDeclarationFunc([NotNull] IsisParser.DeclarationFuncContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.declarationFunc"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitDeclarationFunc([NotNull] IsisParser.DeclarationFuncContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.functionType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFunctionType([NotNull] IsisParser.FunctionTypeContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.functionType"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFunctionType([NotNull] IsisParser.FunctionTypeContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArguments([NotNull] IsisParser.ArgumentsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.arguments"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArguments([NotNull] IsisParser.ArgumentsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.argumentsList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgumentsList([NotNull] IsisParser.ArgumentsListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.argumentsList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgumentsList([NotNull] IsisParser.ArgumentsListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterArgument([NotNull] IsisParser.ArgumentContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.argument"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitArgument([NotNull] IsisParser.ArgumentContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.instructions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstructions([NotNull] IsisParser.InstructionsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.instructions"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstructions([NotNull] IsisParser.InstructionsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.instructionsList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstructionsList([NotNull] IsisParser.InstructionsListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.instructionsList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstructionsList([NotNull] IsisParser.InstructionsListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstruction([NotNull] IsisParser.InstructionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.instruction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstruction([NotNull] IsisParser.InstructionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.instructionIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstructionIf([NotNull] IsisParser.InstructionIfContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.instructionIf"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstructionIf([NotNull] IsisParser.InstructionIfContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.instructionLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstructionLoop([NotNull] IsisParser.InstructionLoopContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.instructionLoop"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstructionLoop([NotNull] IsisParser.InstructionLoopContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.instructionReturn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstructionReturn([NotNull] IsisParser.InstructionReturnContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.instructionReturn"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstructionReturn([NotNull] IsisParser.InstructionReturnContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.instructionBreak"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterInstructionBreak([NotNull] IsisParser.InstructionBreakContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.instructionBreak"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitInstructionBreak([NotNull] IsisParser.InstructionBreakContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterExpression([NotNull] IsisParser.ExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.expression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitExpression([NotNull] IsisParser.ExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.boolExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolExpression([NotNull] IsisParser.BoolExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.boolExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolExpression([NotNull] IsisParser.BoolExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.andExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterAndExpression([NotNull] IsisParser.AndExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.andExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitAndExpression([NotNull] IsisParser.AndExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.notExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNotExpression([NotNull] IsisParser.NotExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.notExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNotExpression([NotNull] IsisParser.NotExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.compareExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompareExpression([NotNull] IsisParser.CompareExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.compareExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompareExpression([NotNull] IsisParser.CompareExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.compareOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCompareOperator([NotNull] IsisParser.CompareOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.compareOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCompareOperator([NotNull] IsisParser.CompareOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.sumExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSumExpression([NotNull] IsisParser.SumExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.sumExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSumExpression([NotNull] IsisParser.SumExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.sumOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterSumOperator([NotNull] IsisParser.SumOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.sumOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitSumOperator([NotNull] IsisParser.SumOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.multExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultExpression([NotNull] IsisParser.MultExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.multExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultExpression([NotNull] IsisParser.MultExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.multOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterMultOperator([NotNull] IsisParser.MultOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.multOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitMultOperator([NotNull] IsisParser.MultOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryExpression([NotNull] IsisParser.UnaryExpressionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.unaryExpression"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryExpression([NotNull] IsisParser.UnaryExpressionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.unaryOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterUnaryOperator([NotNull] IsisParser.UnaryOperatorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.unaryOperator"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitUnaryOperator([NotNull] IsisParser.UnaryOperatorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFactor([NotNull] IsisParser.FactorContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.factor"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFactor([NotNull] IsisParser.FactorContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterVariable([NotNull] IsisParser.VariableContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.variable"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitVariable([NotNull] IsisParser.VariableContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstant([NotNull] IsisParser.ConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.constant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstant([NotNull] IsisParser.ConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.constants"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstants([NotNull] IsisParser.ConstantsContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.constants"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstants([NotNull] IsisParser.ConstantsContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.constantList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterConstantList([NotNull] IsisParser.ConstantListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.constantList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitConstantList([NotNull] IsisParser.ConstantListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.rawNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterRawNumber([NotNull] IsisParser.RawNumberContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.rawNumber"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitRawNumber([NotNull] IsisParser.RawNumberContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.fraction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFraction([NotNull] IsisParser.FractionContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.fraction"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFraction([NotNull] IsisParser.FractionContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.numberConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterNumberConstant([NotNull] IsisParser.NumberConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.numberConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitNumberConstant([NotNull] IsisParser.NumberConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.fractionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterFractionList([NotNull] IsisParser.FractionListContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.fractionList"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitFractionList([NotNull] IsisParser.FractionListContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.charConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterCharConstant([NotNull] IsisParser.CharConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.charConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitCharConstant([NotNull] IsisParser.CharConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.stringConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterStringConstant([NotNull] IsisParser.StringConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.stringConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitStringConstant([NotNull] IsisParser.StringConstantContext context) { }
	/// <summary>
	/// Enter a parse tree produced by <see cref="IsisParser.boolConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void EnterBoolConstant([NotNull] IsisParser.BoolConstantContext context) { }
	/// <summary>
	/// Exit a parse tree produced by <see cref="IsisParser.boolConstant"/>.
	/// <para>The default implementation does nothing.</para>
	/// </summary>
	/// <param name="context">The parse tree.</param>
	public virtual void ExitBoolConstant([NotNull] IsisParser.BoolConstantContext context) { }

	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void EnterEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void ExitEveryRule([NotNull] ParserRuleContext context) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitTerminal([NotNull] ITerminalNode node) { }
	/// <inheritdoc/>
	/// <remarks>The default implementation does nothing.</remarks>
	public virtual void VisitErrorNode([NotNull] IErrorNode node) { }
}
